- community.general.pacman:
    name:
      - cowsay
    state: absent
- community.general.pacman:
    name:
      - git
      - kubectl
      - vim
      - firefox
    state: present
- community.general.pacman:
    name:
      - zsh
- shell:
    cmd: |
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
